IMPLEMENTATION MODULE StrEnum;
(*==========================================================
    Version  : 1.00  29 Apr 1989  C. Lins
    Compiler : TopSpeed Modula-2
    Code Size: R+ 32 bytes, R- 32 bytes
    Component: Tool - String Enumerations Utility

    THE ABSTRACTION
    This module provides enumeration definitions for string
    operations and exceptions.

    REVISION HISTORY
    v1.00  29 Apr 1989  C. Lins:
        Initial implementation.
==========================================================*)

END StrEnum.