#!/bin/sh
mkdir lib
mkdir lwp.lib
mkdir bin
cp conf/sun/* bin
chmod +x bin/m2pp
chmod +x bin/mk_install
mv bin/mainmake makefile
mv fio/bin/depend.sun fio/bin/depend.mak
mv fio/bin/environ.sun fio/bin/environ.mak
mv fio/bin/makefile.sun fio/bin/makefile
mv fio/bin/m2depend.sun fio/bin/m2depend.mak
mv fio/bin/m2source.sun fio/bin/m2source.mak
mv fio/test.bin/depend.sun fio/test.bin/depend.mak
mv fio/test.bin/environ.sun fio/test.bin/environ.mak
mv fio/test.bin/makefile.sun fio/test.bin/makefile
mv fio/test.bin/m2depend.sun fio/test.bin/m2depend.mak
mv fio/test.bin/m2source.sun fio/test.bin/m2source.mak
mv fio/test_lwp.bin/depend.sun fio/test_lwp.bin/depend.mak
mv fio/test_lwp.bin/environ.sun fio/test_lwp.bin/environ.mak
mv fio/test_lwp.bin/makefile.sun fio/test_lwp.bin/makefile
mv fio/test_lwp.bin/m2depend.sun fio/test_lwp.bin/m2depend.mak
mv fio/test_lwp.bin/m2source.sun fio/test_lwp.bin/m2source.mak
mv fio/lwp.bin/depend.sun fio/lwp.bin/depend.mak
mv fio/lwp.bin/environ.sun fio/lwp.bin/environ.mak
mv fio/lwp.bin/makefile.sun fio/lwp.bin/makefile
mv fio/lwp.bin/m2depend.sun fio/lwp.bin/m2depend.mak
mv fio/lwp.bin/m2source.sun fio/lwp.bin/m2source.mak
mv gen/test.bin/depend.sun gen/test.bin/depend.mak
mv gen/test.bin/environ.sun gen/test.bin/environ.mak
mv gen/test.bin/makefile.sun gen/test.bin/makefile
mv gen/test.bin/m2depend.sun gen/test.bin/m2depend.mak
mv gen/test.bin/m2source.sun gen/test.bin/m2source.mak
mv gen/bin/depend.sun gen/bin/depend.mak
mv gen/bin/environ.sun gen/bin/environ.mak
mv gen/bin/makefile.sun gen/bin/makefile
mv gen/bin/m2depend.sun gen/bin/m2depend.mak
mv gen/bin/m2source.sun gen/bin/m2source.mak
mv gen/test_lwp.bin/depend.sun gen/test_lwp.bin/depend.mak
mv gen/test_lwp.bin/environ.sun gen/test_lwp.bin/environ.mak
mv gen/test_lwp.bin/makefile.sun gen/test_lwp.bin/makefile
mv gen/test_lwp.bin/m2depend.sun gen/test_lwp.bin/m2depend.mak
mv gen/test_lwp.bin/m2source.sun gen/test_lwp.bin/m2source.mak
mv gen/lwp.bin/depend.sun gen/lwp.bin/depend.mak
mv gen/lwp.bin/environ.sun gen/lwp.bin/environ.mak
mv gen/lwp.bin/makefile.sun gen/lwp.bin/makefile
mv gen/lwp.bin/m2source.sun gen/lwp.bin/m2source.mak
mv gen/lwp.bin/m2depend.sun gen/lwp.bin/m2depend.mak
mv tools/bin/depend.sun tools/bin/depend.mak
mv tools/bin/environ.sun tools/bin/environ.mak
mv tools/bin/makefile.sun tools/bin/makefile
mv tools/bin/m2depend.sun tools/bin/m2depend.mak
mv tools/bin/m2source.sun tools/bin/m2source.mak
mv demo/lwp.bin/depend.sun demo/lwp.bin/depend.mak
mv demo/lwp.bin/environ.sun demo/lwp.bin/environ.mak
mv demo/lwp.bin/makefile.sun demo/lwp.bin/makefile
mv demo/lwp.bin/m2depend.sun demo/lwp.bin/m2depend.mak
mv demo/lwp.bin/m2source.sun demo/lwp.bin/m2source.mak
mv io/bin/depend.sun io/bin/depend.mak
mv io/bin/environ.sun io/bin/environ.mak
mv io/bin/makefile.sun io/bin/makefile
mv io/bin/m2depend.sun io/bin/m2depend.mak
mv io/bin/m2source.sun io/bin/m2source.mak
mv io/test_lwp.bin/depend.sun io/test_lwp.bin/depend.mak
mv io/test_lwp.bin/environ.sun io/test_lwp.bin/environ.mak
mv io/test_lwp.bin/makefile.sun io/test_lwp.bin/makefile
mv io/test_lwp.bin/m2depend.sun io/test_lwp.bin/m2depend.mak
mv io/test_lwp.bin/m2source.sun io/test_lwp.bin/m2source.mak
mv io/test.bin/depend.sun io/test.bin/depend.mak
mv io/test.bin/environ.sun io/test.bin/environ.mak
mv io/test.bin/makefile.sun io/test.bin/makefile
mv io/test.bin/m2depend.sun io/test.bin/m2depend.mak
mv io/test.bin/m2source.sun io/test.bin/m2source.mak
mv io/lwp.bin/depend.sun io/lwp.bin/depend.mak
mv io/lwp.bin/environ.sun io/lwp.bin/environ.mak
mv io/lwp.bin/makefile.sun io/lwp.bin/makefile
mv io/lwp.bin/m2depend.sun io/lwp.bin/m2depend.mak
mv io/lwp.bin/m2source.sun io/lwp.bin/m2source.mak
