IMPLEMENTATION MODULE CharItems;
(*====================================================================
   Version  : 1.0  Sat, Mar 4, 1989  C. Lins
   Compiler : JPI TopSpeed Modula-2
   Code Size: R-  bytes
   Component: Generic Item Structures - CHAR compatible

    REVISION HISTORY
    v1.0  Sat, Mar 4, 1989  C. Lins
      Initial JPI implementation.

    IMPLEMENTATION DESIGN NOTES
    * The JPI compiler requires an empty implementation module.

    Proprietary Notices
      Copyright (C) 1989 Charles A. Lins. All rights reserved.
====================================================================*)

END CharItems.
