IMPLEMENTATION MODULE IntegerItems;
(*====================================================================
    Version  : 1.0  Sat, Mar 4, 1989  C. Lins
    Compiler : JPI TopSpeed Modula-2
    Code Size: R-  bytes
    Component: Utility - INTEGER Item Type Definitions

    REVISION HISTORY
    v1.0  Sat, Mar 4, 1989  C. Lins
      Initial JPI implementation.

    IMPLEMENTATION ISSUES
    * An empty implementation module is required by the JPI compiler.

    Proprietary Notices
      Copyright (C) 1989 Charles A. Lins. All rights reserved.
====================================================================*)

END IntegerItems.
