IMPLEMENTATION MODULE BagEnum; 

(*====================================================================

    Version  : 1.00  22 Dec 1987  C. Lins

    Compiler : TML Modula-2 Compiler for the Apple Macintosh

    Code Size: R+ 32 bytes, R- 32 bytes

    Component: Structure Utility - Bag Enumerations



    INTRODUCTION

    This module provides enumerations for Bag operations and exceptions.



    REVISION HISTORY

    v1.00  22 Dec 1987  C. Lins:

	  Initial TML Modula-2 implementation.



    PROPRIETARY NOTICES

    "BagEnum.IMP", by C. Lins, Copyright © 1987 Chuck Lins Software.

    5063 Clairemont Mesa Blvd. # 6, San Diego, Calif., USA  92117.

====================================================================*)



END BagEnum.