IMPLEMENTATION MODULE StackEnum; 
(*====================================================================
    Version  : 1.04  07 Jan 1988  C. Lins
    Compiler : TML Modula-2 Compiler for the Apple Macintosh
    Code Size: R+ 32 bytes, R- 32 bytes
    Component: Stack Structure Utility - Standard Enumerations

    THE ABSTRACTION
    This module provides centralized definitions of the operations
    and exceptions for all stack modules.

    REVISION HISTORY
    v1.00  17 Dec 1987  C. Lins:
        Initial TML Modula-2 implementation
    v1.04  07 Jan 1988  C. Lins:
        Recompiled due to changes in DEF module.
====================================================================*)

END StackEnum.