IMPLEMENTATION MODULE GraphTypes;
(*====================================================================
    Version  : V2.01  08 December 1989.
    Compiler : JPI TopSpeed Modula-2
    Code size: 3 bytes
    Component: Graph Structure Utility - Standard Enumerations

    THE ABSTRACTION
    This module provides centralized definitions of the operations
    and exceptions for all graph modules. The TML compiler requires an
    empty implementation module.

    REVISION HISTORY
    v1.00  18 Apr 1988  C. Lins:
      Initial TML Modula-2 implementation
    v2.01  08 Dec 1989  I.S.C. Houston.
      Adapted to JPI Compiler.

====================================================================*)

END GraphTypes.
