IMPLEMENTATION MODULE SetEnum; 

(*====================================================================

    Version  : 1.00  22 Dec 1987  C. Lins

    Compiler : TML Modula-2 Compiler for the Apple Macintosh

    Code Size: R+ 32 bytes, R- 32 bytes

    Component: Structure 



    THE ABSTRACTION

    This module provides definitions of the standard set exceptions

    and operations.  TML requires an empty implementation module.



    REVISION HISTORY

    v1.00  22 Dec 1987  C. Lins:

        Initial TML Modula-2 implementation



    PROPRIETARY NOTICES

    "SetEnum.IMP", by C. Lins, Copyright © 1987 Chuck Lins Software.

    5063 Clairemont Mesa Blvd. # 6, San Diego, Calif., USA  92117.

    Apple is a registered trademark of Apple Computer, Inc.

    Macintosh is a trademark of Apple Computer, Inc.

====================================================================*)



END SetEnum.