IMPLEMENTATION MODULE TreeTypes;
(*====================================================================
    Version  : V2.01  08 December 1989.
    Compiler : JPI TopSpeed Modula-2
    Code size: OBJ file has 580 bytes
    Component: Tree Structure Utility - Standard Enumerations

    THE ABSTRACTION
    This module provides centralized definitions of the operations
    and exceptions for all tree modules. The TML compiler requires an
        empty implementation module.

    REVISION HISTORY
    v1.00  01 Mar 1988  C. Lins:
      Initial TML Modula-2 implementation
    v2.01  08 Dec 1989  I.S.C. Houston.
          Adapted to JPI Compiler.
====================================================================*)

END TreeTypes.
